package com.gn5r;

import java.util.Date;

public class Tutorial {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tutorial.id
     *
     * @mbggenerated Sun Apr 28 17:44:37 JST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tutorial.name
     *
     * @mbggenerated Sun Apr 28 17:44:37 JST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tutorial.email
     *
     * @mbggenerated Sun Apr 28 17:44:37 JST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tutorial.password
     *
     * @mbggenerated Sun Apr 28 17:44:37 JST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tutorial.created
     *
     * @mbggenerated Sun Apr 28 17:44:37 JST 2019
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tutorial.modified
     *
     * @mbggenerated Sun Apr 28 17:44:37 JST 2019
     */
    private Date modified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tutorial.id
     *
     * @return the value of tutorial.id
     *
     * @mbggenerated Sun Apr 28 17:44:37 JST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tutorial.id
     *
     * @param id the value for tutorial.id
     *
     * @mbggenerated Sun Apr 28 17:44:37 JST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tutorial.name
     *
     * @return the value of tutorial.name
     *
     * @mbggenerated Sun Apr 28 17:44:37 JST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tutorial.name
     *
     * @param name the value for tutorial.name
     *
     * @mbggenerated Sun Apr 28 17:44:37 JST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tutorial.email
     *
     * @return the value of tutorial.email
     *
     * @mbggenerated Sun Apr 28 17:44:37 JST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tutorial.email
     *
     * @param email the value for tutorial.email
     *
     * @mbggenerated Sun Apr 28 17:44:37 JST 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tutorial.password
     *
     * @return the value of tutorial.password
     *
     * @mbggenerated Sun Apr 28 17:44:37 JST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tutorial.password
     *
     * @param password the value for tutorial.password
     *
     * @mbggenerated Sun Apr 28 17:44:37 JST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tutorial.created
     *
     * @return the value of tutorial.created
     *
     * @mbggenerated Sun Apr 28 17:44:37 JST 2019
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tutorial.created
     *
     * @param created the value for tutorial.created
     *
     * @mbggenerated Sun Apr 28 17:44:37 JST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tutorial.modified
     *
     * @return the value of tutorial.modified
     *
     * @mbggenerated Sun Apr 28 17:44:37 JST 2019
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tutorial.modified
     *
     * @param modified the value for tutorial.modified
     *
     * @mbggenerated Sun Apr 28 17:44:37 JST 2019
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }
}